### PR TITLE
Add sample gateway chart with luna HSM

### PR DESCRIPTION
**Pull request by alisterz**
Add sample gateway chart with Luna HSM integration

### CODE REVIEW

**Review by gmthomps — CHANGES_REQUESTED** [review]
Please update the readme in the root folder of the integrations repo to add this to the table of available integrations with a short description

**Comment by alisterz** [comment]
> Please update the readme in the root folder of the integrations repo to add this to the table of available integrations with a short description

Readme file updated

**Review by amoghsa — APPROVED** [review]
LGTM.

**Review by gmthomps — APPROVED** [review]
thanks!

**Pull request merged**
